### ISSUE TITLE
Generating skeleton and weights

### ISSUE THREAD

**Issue by szalouk** [dilevin/computer-graphics-final-image-competition#11]
I'm trying to modify A6 to animate a flying bird, but I'm having trouble generating the skeleton, weights and keyframes in the format that is expected by the assignment code. I've gotten a model rigged and animated on Blender, but I can't export the skeleton, weights or keyframes.

Is there a tool that the TA's/Professor would recommend using to generate the skeleton, weights and keyframes to work with the A6 code?

**Comment by darren-moore** [comment]
After some asking around, one recommendation was not to try to directly export the animation, weights, etc, into the exact file formats used in the assignment; rather, to export what you can from Blender, then import those and convert into what you need using libigl. You can trace how each component is imported and used by peeking in `main.cpp` and the `.json` reader used within.

Some thoughts on each:
* **Model:** Done. Can export the `.ply` from Blender
* **Skeleton:** it might be easiest to write the [`.bf` bone forest format](https://libigl.github.io/file-formats/bf/) by hand. It's a special libigl format. I don't see how to export a skeleton from Blender(maybe make a distinguished mesh/obj to get the vertex positions before creating the bone forest structure?)
* **Weights:** [`.dmat` is a matrix format](https://libigl.github.io/file-formats/dmat/). I don't see how to export weights into this format in Blender. It seems you can export weights as a UV map that you can map into a matrix using libigl.
* **Keyframes:** These all live in the `.json`, which looks to be automatically generated. Your best bet might be to use the assignment's live poser, then add a command to export the bone transform keyframes to a `.json` or whatever format you want.

Most file formats don't include a lot of data, except for the elusive `.fbx`, which seems to include everything. One option could be to export from Blender as an `.fbx`, then use the [`.fbx` SDK](https://www.autodesk.com/products/fbx/overview) to assist. libigl does not support `.fbx` yet.
