### ISSUE TITLE
Merging A3 and A4

### ISSUE THREAD

**Issue by MhiriMoh** [dilevin/computer-graphics-final-image-competition#5]
I am trying to speed up my intersection calculation from ray tracing by adding an AABB tree. I went through all the code where intersection math is calculated and changed it such that it uses the AABB methods, I have also went through and included all the necessary include files. However when i try to make I get a set of errors around the abstract object types that I can't quite figure out. Im just wondering how the objects were structured for the bounding box labs and how they are different than the ray tracing lab and how can I resolve these differences.

The following is the outputted error text:

[error.txt](https://github.com/dilevin/computer-graphics-final-image-competition/files/4412060/error.txt)

**Comment by darren-moore** [comment]
Nice idea, and thanks for including the error logs in your question. One issue is that the `Object` class is defined differently in each assignment. It looks like you merged them? All the A3 objects are now missing implementations of the `ray_intersect` and `point_squared_distance` functions (which are pure virtual and require implementations in derived classes). This is causing most of the errors.

Consider using namespaces to differentiate each assignment's `Object`. To help more, I'll need to familiarize myself with A4 a bit more. Will report back!
